// Generated by CoffeeScript 1.7.1
(function() {
  var Featurette;

  Featurette = (function() {
    function Featurette() {}

    Featurette.version = "1.2.0";

    Featurette.registered_features = {};

    Featurette.featurettes_counter = 0;

    Featurette.register = function(name, klass) {
      return this.registered_features[name] = klass;
    };

    Featurette.load = function() {
      var element, featurette, id, klass, obj, _i, _len, _ref, _results;
      _ref = document.querySelectorAll("[data-featurette]");
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        element = _ref[_i];
        featurette = element.getAttribute("data-featurette");
        klass = this.registered_features[featurette];
        if (klass) {
          id = element.id;
          if (!element.featurette) {
            if ((id == null) || id === "") {
              id = "featurette-" + this.featurettes_counter;
              element.id = id;
            }
            obj = new klass(element);
            element.featurette = obj;
            _results.push(this.featurettes_counter += 1);
          } else {
            _results.push(void 0);
          }
        } else {
          if (window.console) {
            _results.push(console.log("Unknown featurette " + featurette));
          } else {
            _results.push(void 0);
          }
        }
      }
      return _results;
    };

    Featurette.get = function(id) {
      var _ref;
      return (_ref = document.getElementById(id)) != null ? _ref.featurette : void 0;
    };

    return Featurette;

  })();

  window.Featurette = Featurette;

}).call(this);
