// Generated by CoffeeScript 1.6.3
(function() {
  var Featurette;

  Featurette = (function() {
    function Featurette() {}

    Featurette.version = "1.2.0";

    Featurette.registered_features = {};

    Featurette.featurettes_counter = 0;

    Featurette.register = function(name, klass) {
      return this.registered_features[name] = klass;
    };

    Featurette.load = function() {
      var element, elements, elementsNeedingLoad, featurette, id, klass, obj, _i, _j, _len, _len1, _results;
      elementsNeedingLoad = document.querySelectorAll("[data-featurette]");
      elements = [];
      for (_i = 0, _len = elementsNeedingLoad.length; _i < _len; _i++) {
        element = elementsNeedingLoad[_i];
        if (!(element.featuretteLoading || element.featurette)) {
          elements.push(element);
          element.featuretteLoading = true;
        }
      }
      _results = [];
      for (_j = 0, _len1 = elements.length; _j < _len1; _j++) {
        element = elements[_j];
        featurette = element.getAttribute("data-featurette");
        klass = this.registered_features[featurette];
        if (klass) {
          id = element.id;
          if ((id == null) || id === "") {
            id = "featurette-" + this.featurettes_counter;
            element.id = id;
          }
          obj = new klass(element);
          element.featurette = obj;
          _results.push(this.featurettes_counter += 1);
        } else {
          if (window.console) {
            _results.push(console.log("Unknown featurette " + featurette));
          } else {
            _results.push(void 0);
          }
        }
      }
      return _results;
    };

    Featurette.get = function(id) {
      var _ref;
      return (_ref = document.getElementById(id)) != null ? _ref.featurette : void 0;
    };

    return Featurette;

  })();

  window.Featurette = Featurette;

}).call(this);
